spring.application.name=BE

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/ltw
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Security
jwt.secret=Tu7wKp7JH8h3kQvXnE1Y5pWmZsR9tB2cD4fGhIjKlMnO=
jwt.expiration=60000
jwt.refresh-token-expiration = 60000
server.port=8082